export const REQUEST_POSTS = 'REQUEST_POSTS';
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS';
export const REQUEST_POSTS_ERROR = 'REQUEST_POSTS_ERROR';

export const REQUEST_SINGLE_POST = 'REQUEST_SINGLE_POST';
export const REQUEST_SINGLE_POST_SUCCESS = 'REQUEST_SINGLE_POST_SUCCESS';
export const REQUEST_SINGLE_POST_ERROR = 'REQUEST_SINGLE_POST_ERROR';

export const REQUEST_CREATE_COMMENT = 'REQUEST_CREATE_COMMENT';
export const REQUEST_CREATE_COMMENT_SUCCESS = 'REQUEST_CREATE_COMMENT_SUCCESS';
export const REQUEST_CREATE_COMMENT_ERROR = 'REQUEST_CREATE_COMMENT_ERROR';